---
- name: "Install Dependencies"
  apt:
    name: "{{item}}"
    state: "present"
  loop:
  - "python-pip"
  - "python-virtualenv"
  tags: [ never, infra ]

- name: "Create python VirtualEnv in {{ansible_inst_path}}"
  pip:
    name: "ansible"
    version: "{{ ansible_inst_ver }}"
    virtualenv: "{{ ansible_inst_path }}"
  tags: [ never, infra ]