---
- name: "Install Dependencies"
  apt:
    name:
    - "python3-minimal"
    - "python-pip"
    - "python-virtualenv"
    - "python-setuptools"
    state: "present"
  tags: [ never, infra ]

- name: "Create python VirtualEnv in {{ansible_inst_path}}"
  pip:
    name: "ansible"
    version: "{{ ansible_inst_ver }}"
    virtualenv: "{{ ansible_inst_path }}"
    virtualenv_python: "{{ ansible_venv_python }}"
    state: "{{ ansible_inst_state }}"
  tags: [ never, infra ]